DROP TABLE user_roles IF EXISTS ;
DROP TABLE users IF EXISTS;
DROP TABLE menu IF EXISTS;
DROP TABLE restaurants IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER START WITH 10000;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    login            VARCHAR(255)                           NOT NULL,
    password         VARCHAR(255)                           NOT NULL,
    email            VARCHAR(255)                           NOT NULL,
    registered       TIMESTAMP(0)             DEFAULT now() NOT NULL,
    enabled          BOOLEAN                  DEFAULT TRUE  NOT NULL,
    restaurant_id    INTEGER                  DEFAULT NULL
);
CREATE UNIQUE INDEX email_index ON users (email);

CREATE TABLE user_roles
(
    user_id         INTEGER                                 NOT NULL,
    role            VARCHAR(255),
    CONSTRAINT user_roles_index UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE restaurants
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name            VARCHAR(255)                            NOT NULL,
    vote_counter    INTEGER                                 DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE menu
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    restaurant_id   INTEGER,
    dish            VARCHAR(255)                            NOT NULL,
    price           REAL                                    NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
)